# Generated by Django 4.2 on 2023-04-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parcers_v1", "0002_items_resource_delete_parcer_items_res_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="nd_date",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="items",
            name="not_date",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="items",
            name="s_date",
            field=models.CharField(max_length=255),
        ),
    ]
